version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${DOCK_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DOCK_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCK_DB_PASSWORD}
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCK_DB_SCHEMA}
      MYSQL_USER: ${DOCK_DB_USERNAME}
      MYSQL_PASSWORD: ${DOCK_DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
