server:
    port: 8080
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    web:
        resources:
            mime:
                types:
                    map: application/json
    jpa:
        show-sql: true
        properties:
            hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
    datasource:
        url: jdbc:mysql://localhost:3306/ezbook?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver